# Generated by Django 3.2.4 on 2021-06-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='name',
        ),
    ]
